version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sahil
      MONGO_INITDB_ROOT_PASSWORD: 980980
      MONGO_INITDB_DATABASE: online-tutor
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
